### ISSUE TITLE
Tests Fail Due to API_KEY Being Undefined

### ISSUE THREAD

**Issue by schmalzs** [bmorelli25/ReactWeather#28]
Right now, the tests fail out-of-the-box because `API_KEY` will be undefined.  In order to make them work, you need to manually set the value of `API_KEY` in `openWeatherMap.jsx` while running the tests.

I'd like to fix this so that you don't need to manually set the value of `API_KEY` and, instead, your API key will be retrieved from the `.env` file.

**Comment by bmorelli25** [comment]
Good find. It appears I didn't initially get the error because I had already input the environment variable in the command line (as was required before #2). When I clear it out, I get the same error your showing. 

 I think the error is being caused because `require('dotenv').config()` is being called in `webpack.config.js`. This line has to be called before the `openWeatherMap.jsx` file is required.  In production, it is, however `webpack.config.js` is never used when running tests and thus never called. 

And, yup, looks like you've just submitted a PR, I'll take a look

**Comment by bmorelli25** [comment]
#29
